name: Reset Firebase Points

on:
  schedule:
    # - cron: "0 5 20 * *" # Ejecuta a las 12:00 AM hora de Colombia (5:00 AM UTC)
    - cron: "40 14 20 * *" # Ejecuta a las 12:00 AM hora de Colombia (9:30 AM UTC)

  # workflow_dispatch:

jobs:
  reset:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Create service account key file
        env:
          SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        run: echo "$SERVICE_ACCOUNT_KEY" > ./serviceAccountKey.json

      - name: Run reset script
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ./serviceAccountKey.json
        run: node resetPoints.js
